### ISSUE TITLE
Move experimentation report from post-processor to reporting-worker

### ISSUE THREAD

**Issue by ekremney** [adobe/spacecat-api-service#226]
To-Do:
1. Experimentation reporting related logic should be moved from post-processor to [reporting-worker](https://github.com/adobe/spacecat-reporting-worker)
2. Have two separate schedules for audits & reports:
   1. Audits should be daily
   2. Reports should be weekly

**Comment by raji-unni** [comment]
This is completed - https://github.com/adobe/spacecat-reporting-worker/pull/4
