### ISSUE TITLE
Cannot create a new import job without `options`

### ISSUE THREAD

**Issue by blefebvre** [adobe/spacecat-api-service#353]
**Description**
The `options` object is an optional property in the JSON request body, but currently it is required in order to start a new import job.

**To Reproduce**
```
$ curl -v -H "x-api-key: $SPACECAT_API_KEY" -H "x-import-api-key: $IMPORT_API_KEY" -H "Content-Type: application/json" \
--request POST --data '{ "urls": ["https://www.brucelefebvre.com/page1.html", "https://www.brucelefebvre.com/page2.html"] }' \
https://spacecat.experiencecloud.live/api/ci/tools/import
...
< HTTP/2 500
...
< x-error: Invalid options: undefined
```

**Expected behavior**
An import job should be able to be created without this object, and the default values for all options should be assumed in its absence.

**Comment by swetabar** [comment]
Resolved.
